export const quotes = [
    { text: "Houston, we have a problem.", author: "Apollo 13" },
    { text: "I’ve made a huge mistake.", author: "Arrested Development" },
    { text: "This is not the droid you’re looking for.", author: "Star Wars" },
    { text: "I am serious. And don’t call me Shirley.", author: "Airplane!" },
    { text: "We’re gonna need a bigger boat.", author: "Jaws" },
    { text: "D’oh!", author: "The Simpsons" },
    { text: "It’s dead, Jim.", author: "Star Trek" },
    { text: "Danger, Will Robinson!", author: "Lost in Space" },
    { text: "Well, nobody’s perfect.", author: "Some Like It Hot" },
    { text: "I'm sorry, Dave. I'm afraid I can't do that.", author: "2001: A Space Odyssey" },
    { text: "The night is dark and full of terrors.", author: "Game of Thrones" },
    { text: "You know nothing, Jon Snow.", author: "Game of Thrones" },
    { text: "I find your lack of faith disturbing.", author: "Star Wars" },
    { text: "Why is the rum always gone?", author: "Pirates of the Caribbean" },
    { text: "Looks like we’re not in Kansas anymore.", author: "The Wizard of Oz" },
    { text: "I've seen enough to know I've seen too much.", author: "The Simpsons" },
    { text: "Chaos is a ladder.", author: "Game of Thrones" },
    { text: "I’ve got a bad feeling about this.", author: "Star Wars" },
    { text: "You keep using that word. I do not think it means what you think it means.", author: "The Princess Bride" },
    { text: "So this is how liberty dies… with thunderous applause.", author: "Star Wars: Revenge of the Sith" },
    { text: "Something's not quite right.", author: "Doctor Who" },
    { text: "Do you feel lucky, punk?", author: "Dirty Harry" },
    { text: "It's not over until I say it's over!", author: "Animal House" },
    { text: "Don't panic!", author: "The Hitchhiker’s Guide to the Galaxy" },
    { text: "The world isn’t perfect. But it’s there for us.", author: "Fullmetal Alchemist: Brotherhood" },
    { text: "Oops, I did it again.", author: "Britney Spears (Okay, not a movie but still fun!)" }
  ];
  